// <auto-generated />
using System;
using Dystopia.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dystopia.Migrations
{
    [DbContext(typeof(PolydystopiaDbContext))]
    [Migration("20250806090745_AddGameOwnerRelation")]
    partial class AddGameOwnerRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("Dystopia.Database.Friendship.FriendshipEntity", b =>
                {
                    b.Property<Guid>("UserId1")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId2")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserEntityId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId1", "UserId2");

                    b.HasIndex("UserEntityId");

                    b.HasIndex("UserId2");

                    b.ToTable("Friends");
                });

            modelBuilder.Entity("Dystopia.Database.Game.GameEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("CurrentGameStateData")
                        .HasColumnType("BLOB");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCurrentTurnDeadline")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateLastCommand")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ExternalMatchId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ExternalTournamentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameSettings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("InitialGameStateData")
                        .HasColumnType("BLOB");

                    b.Property<Guid?>("OwnerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimerSettings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Dystopia.Database.Lobby.LobbyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Bots")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ChallengermodeGameId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisabledTribes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ExternalMatchId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ExternalTournamentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InviteLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MapPreset")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MapSize")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MatchmakingGameId")
                        .HasColumnType("INTEGER");

                    b.Property<short>("MaxPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ScoreLimit")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StartedGameId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeLimit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Lobbies");
                });

            modelBuilder.Entity("Dystopia.Database.Matchmaking.MatchmakingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowCrossPlay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameMode")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LobbyEntityId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MapPreset")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MapSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Platform")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ScoreLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LobbyEntityId");

                    b.ToTable("Matchmaking");
                });

            modelBuilder.Entity("Dystopia.Database.News.NewsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Link")
                        .HasColumnType("TEXT");

                    b.Property<int>("NewsType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("News");
                });

            modelBuilder.Entity("Dystopia.Database.Replay.UserFavoriteGame", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MarkedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("UserFavoriteGames");
                });

            modelBuilder.Entity("Dystopia.Database.User.GameParticipatorUserEntity", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCurrentTurnDeadline")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateLastCommand")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateLastEndTurn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateLastStartTurn")
                        .HasColumnType("TEXT");

                    b.Property<int>("InvitationState")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("LastConsumedTimeBank")
                        .HasColumnType("TEXT");

                    b.Property<int>("SelectedTribe")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectedTribeSkin")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("TimeBank")
                        .HasColumnType("TEXT");

                    b.HasKey("GameId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("GameParticipators");
                });

            modelBuilder.Entity("Dystopia.Database.User.LobbyParticipatorUserEntity", b =>
                {
                    b.Property<Guid>("LobbyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("InvitationState")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectedTribe")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectedTribeSkin")
                        .HasColumnType("INTEGER");

                    b.HasKey("LobbyId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("LobbyParticipators");
                });

            modelBuilder.Entity("Dystopia.Database.User.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowsFriendRequests")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("AvatarStateData")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<int>("Elo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameVersions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastLoginDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SteamId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Dystopia.Database.Friendship.FriendshipEntity", b =>
                {
                    b.HasOne("Dystopia.Database.User.UserEntity", null)
                        .WithMany("Friends")
                        .HasForeignKey("UserEntityId");

                    b.HasOne("Dystopia.Database.User.UserEntity", "User1")
                        .WithMany()
                        .HasForeignKey("UserId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dystopia.Database.User.UserEntity", "User2")
                        .WithMany()
                        .HasForeignKey("UserId2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("Dystopia.Database.Game.GameEntity", b =>
                {
                    b.HasOne("Dystopia.Database.User.UserEntity", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Dystopia.Database.Matchmaking.MatchmakingEntity", b =>
                {
                    b.HasOne("Dystopia.Database.Lobby.LobbyEntity", "LobbyEntity")
                        .WithMany()
                        .HasForeignKey("LobbyEntityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("LobbyEntity");
                });

            modelBuilder.Entity("Dystopia.Database.Replay.UserFavoriteGame", b =>
                {
                    b.HasOne("Dystopia.Database.Game.GameEntity", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dystopia.Database.User.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dystopia.Database.User.GameParticipatorUserEntity", b =>
                {
                    b.HasOne("Dystopia.Database.Game.GameEntity", "Game")
                        .WithMany("Participators")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dystopia.Database.User.UserEntity", "User")
                        .WithMany("GameParticipations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dystopia.Database.User.LobbyParticipatorUserEntity", b =>
                {
                    b.HasOne("Dystopia.Database.Lobby.LobbyEntity", "Lobby")
                        .WithMany("Participators")
                        .HasForeignKey("LobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dystopia.Database.User.UserEntity", "User")
                        .WithMany("LobbyParticipations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lobby");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dystopia.Database.Game.GameEntity", b =>
                {
                    b.Navigation("Participators");
                });

            modelBuilder.Entity("Dystopia.Database.Lobby.LobbyEntity", b =>
                {
                    b.Navigation("Participators");
                });

            modelBuilder.Entity("Dystopia.Database.User.UserEntity", b =>
                {
                    b.Navigation("Friends");

                    b.Navigation("GameParticipations");

                    b.Navigation("LobbyParticipations");
                });
#pragma warning restore 612, 618
        }
    }
}
