// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PolytopiaB2.Carrier.Database;

#nullable disable

namespace PolytopiaB2.Carrier.Migrations
{
    [DbContext(typeof(PolydystopiaDbContext))]
    [Migration("20250619190204_DeleteLobbyMatchmakingCascade")]
    partial class DeleteLobbyMatchmakingCascade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("PolytopiaB2.Carrier.Database.Friendship.FriendshipEntity", b =>
                {
                    b.Property<Guid>("UserId1")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId2")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId1", "UserId2");

                    b.HasIndex("UserId2");

                    b.ToTable("Friends");
                });

            modelBuilder.Entity("PolytopiaB2.Carrier.Database.Matchmaking.MatchmakingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowCrossPlay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameMode")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LobbyGameViewModelId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MapPreset")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MapSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Platform")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ScoreLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LobbyGameViewModelId");

                    b.ToTable("Matchmaking");
                });

            modelBuilder.Entity("PolytopiaB2.Carrier.Database.News.NewsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Link")
                        .HasColumnType("TEXT");

                    b.Property<int>("NewsType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("News");
                });

            modelBuilder.Entity("PolytopiaBackendBase.Auth.PolytopiaUserViewModel", b =>
                {
                    b.Property<Guid>("PolytopiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Alias")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowsFriendRequests")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("AvatarStateData")
                        .HasColumnType("BLOB");

                    b.Property<string>("CmUserData")
                        .HasColumnType("TEXT");

                    b.Property<string>("Defeats")
                        .HasColumnType("TEXT");

                    b.Property<int>("Elo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FriendCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameVersions")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MultiplayerRating")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NumFriends")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NumGames")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NumMultiplayergames")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SteamId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnlockedSkins")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnlockedTribes")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UserMigrated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Victories")
                        .HasColumnType("TEXT");

                    b.HasKey("PolytopiaId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PolytopiaBackendBase.Game.GameViewModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("CurrentGameStateData")
                        .HasColumnType("BLOB");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCurrentTurnDeadline")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateLastCommand")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameContext")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameSettingsJson")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("InitialGameStateData")
                        .HasColumnType("BLOB");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimerSettings")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("PolytopiaBackendBase.Game.LobbyGameViewModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Bots")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ChallengermodeGameId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisabledTribes")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameContext")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InviteLink")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPersistent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSharable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MapPreset")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MapSize")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MatchmakingGameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<short>("OpponentCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Participators")
                        .HasColumnType("TEXT");

                    b.Property<int>("ScoreLimit")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StartedGameId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UpdatedReason")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Lobbies");
                });

            modelBuilder.Entity("PolytopiaB2.Carrier.Database.Friendship.FriendshipEntity", b =>
                {
                    b.HasOne("PolytopiaBackendBase.Auth.PolytopiaUserViewModel", "User1")
                        .WithMany()
                        .HasForeignKey("UserId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PolytopiaBackendBase.Auth.PolytopiaUserViewModel", "User2")
                        .WithMany()
                        .HasForeignKey("UserId2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("PolytopiaB2.Carrier.Database.Matchmaking.MatchmakingEntity", b =>
                {
                    b.HasOne("PolytopiaBackendBase.Game.LobbyGameViewModel", "LobbyGameViewModel")
                        .WithMany()
                        .HasForeignKey("LobbyGameViewModelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("LobbyGameViewModel");
                });
#pragma warning restore 612, 618
        }
    }
}
