name: Build and Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false

      - name: Set up SSH key for submodule
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.LIB_SUBMODULE_SSH_KEY }}

      - name: Clone private submodule
        uses: pietrobolcato/action-clone-private-submodule@v1.0.2
        with:
          ssh_private_key: ${{ secrets.LIB_SUBMODULE_SSH_KEY }}
          module_link: Polydistopia/DystopiaLibs
          module_path: lib

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal
