name: Build and Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false

      - name: Set up SSH key for submodule
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.LIB_SUBMODULE_SSH_KEY }}

      - name: Clone private submodule
        uses: pietrobolcato/action-clone-private-submodule@v1.0.2
        with:
          module_link: Polydystopia/DystopiaLibs
          module_path: lib

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Restore & Build
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore

      - name: Upload build outputs
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            **/bin/Release/**

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false

      - name: Download build outputs
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: ./build

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Run Tests
        run: dotnet test Dystopia.sln --no-build --configuration Release --verbosity normal
